image: node:8.11.1

cache:
  paths:
    - node_modules/

stages:
  - test

test_lint:
  stage: test
  script:
   - npm set registry http://51.15.253.55:4873
   - npm install
   - npm install -g typescript
   - tsc
   - npm run lint