language: node_js
cache:
  directories:
    - "node_modules"
script:
  - npm set registry http://51.15.253.55:4873
  - npm install
  - npm install -g typescript
  - tsc
  - npm run lint
  - npm run test