language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: 8
after_success:
  - npm run travis-deploy-once "npm run semantic-release --skip-ci && npm run docs && git add . && git commit -m \"build(documentation) Generated documentation for latest changes.\" && git push"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
